spring:
  application:
    name: Sub-ai-agent
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 60000
#  profiles:
#    active: local

  #spring:
#  application:
#    name: spring-ai-alibaba-qwq-chat-client-example
  ai:
    dashscope:
      api-key: sk-79f3296fd84c4c1ab9e8cf4fc9001013
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#        initialize-schema: true # 自动创建表
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/ai_agent?useSSL=false&serverTimezone=UTC
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      url: jdbc:postgresql://192.168.20.141/sub_ai_agent
      username: submerge
      password: WangDong0288
      driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.submerge.subaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.org.springframework.ai.chat.client.advisor.MyLoggerAdvisor: debug
